swagger: "2.0"
info:
  title: Professors API
  description: API description in Markdown.
  version: 1.0.0
basePath: /v1
schemes:
  - http
  - https
paths:
  /professors:
    get:
      summary: Returns a list of professors.
      operationId: getProfessors
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/ProfessorApiSpec'
    post:
      summary: Creates a new professor.
      operationId: createProfessor
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: body
          name: professor
          schema:
            $ref: '#/definitions/ProfessorApiSpec'
      responses:
        201:
          description: Created
          schema:
            $ref: '#/definitions/ProfessorApiSpec'
  /professors/{professorId}:
    get:
      summary: Returns a professor by ID.
      operationId: getProfessorById
      produces:
        - application/json
      parameters:
        - in: path
          name: professorId
          required: true
          type: integer
          minimum: 1
          description: The ID of the professor to retrieve.
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/ProfessorApiSpec'
        400:
          description: The specified professor ID is invalid (e.g. not a number).
        404:
          description: A professor with the specified ID was not found.
        default:
          description: Unexpected error
    put:
      summary: Update / Replace a professor.
      operationId: updateProfessor
      consumes:
        - application/json
      parameters:
        - in: path
          name: professorId
          required: true
          type: integer
          minimum: 1
          description: The ID of the professor to update.
        - in: body
          name: professor
          schema:
            $ref: '#/definitions/ProfessorApiSpec'
      reponses:
        204:
          description: No Content
        400:
          description: The specified professor ID is invalid (e.g. not a number).
        404:
          description: A professor with the specified ID was not found.
        default:
          description: Unexpected error
    delete:
      summary: Delete a professor.
      operationId: deleteProfessor
      parameters:
          - in: path
            name: professorId
            required: true
            type: integer
            minimum: 1
            description: The ID of the professor to delete.
      reponses:
        200:
          description: Deleted
        400:
          description: The specified professor ID is invalid (e.g. not a number).
        404:
          description: A professor with the specified ID was not found.
        default:
          description: Unexpected error
definitions:
  ProfessorApiSpec:
    properties:
      id:
        type: integer
      name:
        type: string
    required:
      - name